name: build-push-docker-image

on:
  push:
    branches:
      - "master"
      

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/miao:next

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODHOST }}
          username: ${{ secrets.PRODUSERNAME }}
          password: ${{ secrets.PRODPASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop miao
            docker rm miao
            docker pull zdeteam/miao:next
            docker run -d --name miao --restart always -p 5005:5005 -v /home/flame/data:/app/data -e PASSWORD=abc123pwd! zdeteam/miao:next
